

services:
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring_boot_app
    ports:
      - "5000:5000"    
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg-3350361-kasundilumina2016-fd51.d.aivencloud.com:24658/defaultdb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=avnadmin
      - SPRING_DATASOURCE_PASSWORD=AVNS_W6ko1AyVESlwkdEqaoe  
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network


networks:
  app_network: