version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    container_name: spring_boot_app
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/moview_review
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 8482
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    container_name: react_app
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:
